name: 'Sync develop'
description: 'This action help to automatically synchronize the develop branch, once is merge and squash with main'
inputs:
  ssh-key-name:
    description: >
      The name of the secret that contains the SSH key used to fetch the repository.
    default: "SSH_PRIVATE_KEY"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - shell: bash
      run: |
        ./ssh-config/configure.sh
      env:
        SSH_KEY_NAME: ${{ inputs.ssh-key-name }}
        RELEASE_EMAIL: ${{ vars.RELEASE_EMAIL }}
        REPO: ${{ github.repository }}
