name: 'SSH Key Generation'
description: 'This action help to automatically generate the ssh keys, store the private key in a secret and the public is set in the deploy keys of the repository.'
inputs:
  ssh-key-name:
    description: >
      The name of the secret that will have the ssh key.
    default: "SSH_PRIVATE_KEY"
  repo:
    description: 'The repository were you want to create the secret.'
    default: ${{ github.repository }}
  user-email:
    description: 'The email of the user that will be used to generate the ssh key'
    required: true
  token:
    description: >
      The token use to store the key in the secrets
    required: true
outputs:
  ssh-key:
    description: 'ssh key generated'
    value: "${{ steps.ssh_gen.outputs.ssh_key }}"
  test-data:
    description: 'test'
    value: "${{ steps.ssh_gen.outputs.test }}"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: pcistudio/actions
        ref: v1
        path: ./pcistudio_actions
    - id: ssh_gen
      shell: bash
      run: |
        set -e
        set -x

        #[ -z "SSH_KEY" ] && echo "SSH_KEY is not set" && exit 1
        echo "test=data365" >> $GITHUB_OUTPUT
        KEY_PATH="$HOME/.ssh/id_ed25519"
        PUB_KEY_PATH="${KEY_PATH}.pub"

        echo "Creating SSH key for ${REPO}"
        mkdir -p ~/.ssh
        ssh-keygen -t ed25519 -f "${KEY_PATH}" -N "" -C "${RELEASE_EMAIL}" > /dev/null
        
        {
          echo 'ssh_key<<EOF'
          cat "$HOME/.ssh/id_ed25519"
          echo EOF
        } >> "$GITHUB_OUTPUT"

#        SSH_PRIV=$(cat "${KEY_PATH}");
#        echo "ssh_key=${SSH_PRIV}" >> $GITHUB_OUTPUT

      env:
        SSH_KEY_NAME: ${{ inputs.ssh-key-name }}
        RELEASE_EMAIL: ${{ inputs.user-email }}
        REPO: ${{ inputs.repo }}
        GH_TOKEN: ${{ inputs.token }}
        GITHUB_OUTPUT: $GITHUB_OUTPUT
#    - name: Set the value in bash
#      id: step_one
#      shell: bash
#      run: |
#        {
#          echo 'ssh_key<<EOF'
#          cat "$HOME/.ssh/id_ed25519"
#          echo EOF
#        } >> "$GITHUB_OUTPUT"
    - name: "Test"
      shell: bash
      run: |
        echo "The modified secret is: ${{ steps.ssh_gen.outputs.test }}"
#        [ -z "${{ steps.step_one.outputs.ssh_key }}" ] && echo "No Key" || echo "KEY present"
        [ -z "${{ steps.ssh_gen.outputs.ssh_key }}" ] && echo "No Key" || echo "KEY present"
        
        

        
        

