name: 'SSH Key Generation'
description: 'This action help to automatically generate the ssh keys, store the private key in a secret and the public is set in the deploy keys of the repository.'
inputs:
  ssh-key-name:
    description: >
      The name of the secret that will have the ssh key.
    default: "SSH_PRIVATE_KEY"
  repo:
    description: 'The repository were you want to create the secret.'
    default: ${{ github.repository }}
  user-email:
    description: 'The email of the user that will be used to generate the ssh key'
    required: true
  token:
    description: >
      The token use to store the key in the secrets
    required: true
outputs:
  ssh-key:
    description: 'ssh key generated'
    value: ${{ steps.ssh-gen.outputs.ssh_key }}
  test-data:
    description: 'test'
    value: ${{ steps.ssh-gen.outputs.test }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: pcistudio/actions
        ref: v1
        path: ./pcistudio_actions
    - id: ssh-gen
      shell: bash
      run: |
        ./pcistudio_actions/ssh-gen/configure.sh
        echo "test=data360" >> $GITHUB_OUTPUT
      env:
        SSH_KEY_NAME: ${{ inputs.ssh-key-name }}
        RELEASE_EMAIL: ${{ inputs.user-email }}
        REPO: ${{ inputs.repo }}
        GH_TOKEN: ${{ inputs.token }}
#        SSH_KEY: ${{ secrets.${{ inputs.ssh-key-name }} }}

