name: 'Setup SSH Key'
description: 'This action help to automatically configure the ssh keys in the `.ssh` folder, so you can use it in your scripts.'
inputs:
  ssh-key:
    description: >
      SSH key used to fetch the repository. The SSH key is configured with the local
      git config, which enables your scripts to run authenticated git commands.
runs:
  using: "composite"
  steps:
    - name: Set up SSH
      shell: bash
      run: |
        if [ -n "${{ inputs.ssh-key }}" ]; then
          mkdir -p ~/.ssh
          echo "${{ inputs.ssh-key }}" > ~/.ssh/id_ed25519  
          echo "SSH key is set as input parameter"
        else 
            echo "SSH key is not set as input"
            echo "Checking for ~/.ssh/id_ed25519"
            if [ ! -f ~/.ssh/id_ed25519 ]; then
                echo "SSH key is not configured in the in ~/.ssh/id_ed25519"
                exit 1
            else
                echo "SSH key is configured in the in ~/.ssh/id_ed25519"
            fi
        fi
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

