name: Release actions

on:
  push:
    branches:
      - main
env:
  MAJOR_VERSION: v1
  VERSION: v1.${{ github.run_number }}
jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create Release
        run: gh release create ${{ env.VERSION }} -t "Release ${{ env.VERSION }}" -n "Release ${{ env.VERSION }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Git Author
        run: |
          git config --global user.name "${{ vars.RELEASE_USER }}"
          git config --global user.email "${{ vars.RELEASE_EMAIL }}"
      - name: Update Major Version Tag to Latest Release
        run: |
          git tag -fa ${{ env.MAJOR_VERSION }} -m "Update ${{ env.MAJOR_VERSION }} to latest release"
          git push origin ${{ env.MAJOR_VERSION }} --force