name: Release actions

on:
  push:
    branches:
      - 5-create-ssh-config-action
env:
  MAJOR_VERSION: v1
  VERSION: v1.${{ github.run_number }}
jobs:
  ssh-config:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH Key
        uses: pcistudio/actions/ssh-config@5-create-ssh-config-action