name: Release actions

on:
  push:
    branches:
      - bugfix/ssh-gen

jobs:
  ssh-key-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH Key
        uses: pcistudio/actions/ssh-gen@bugfix/ssh-gen
        with:
          ssh-key-name: "SSH_PRIVATE_KEY"
          repo: ${{ github.repository }}
          user-email: ${{ vars.RELEASE_EMAIL }}
          token: ${{ secrets.GIT_ADMIN_PAT }}
        env:
          GH_TOKEN: ${{ secrets.GIT_ADMIN_PAT }}
